version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: bitcoin-trading-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    command: serve

  trading-agent:
    build: .
    container_name: bitcoin-trading-agent
    depends_on:
      - ollama
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped
    command: python main.py

volumes:
  ollama_data: